{{- if and .Values.thanos.query.enabled .Values.thanos.query.basicAuth.authSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-thanos-query-grpc
  labels:
    {{ .Values.datasource.auto_load_label }}: "True"
    app: {{ template "k8s-thanos.name" . }}
    chart: {{ template "k8s-thanos.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  auth: {{ .Values.thanos.query.basicAuth.authSecret }}
{{- end }}
