{{- if .Values.configMaps }}
{{- $root := . -}}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/inline-mutation: "true"
  name: {{ .name }}
  labels:
    app: {{ $root.Values.appName }}
    {{- range $k, $v := .labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
data:
{{- range $k, $v := .data }}
  {{ $k}}: |-
{{ $v | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
