{{- $root := . -}}

{{- range .Values.cronjobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-{{ .name }}
  labels:
    app: {{ $root.Values.appName }}-cron
    chart: k8s-generic-service
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}

spec:
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit | default 3 }}
  concurrencyPolicy: {{ .concurrencyPolicy | default "Allow" }}
  jobTemplate:
    spec:
      backoffLimit: {{ .backoffLimit | default 0 }}
      {{- if .activeDeadlineSeconds }}
      activeDeadlineSeconds:
{{ toYaml .activeDeadlineSeconds | indent 8 }}
      {{- end }}
      template:
        metadata:
          labels:
            app: {{ $root.Values.appName }}-job
          annotations:
            {{- if $root.Values.vault.enabled }}
            vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
            vault.security.banzaicloud.io/vault-skip-verify: "true"
            {{- end }}
            sidecar.istio.io/inject: "false" # Jobs cannot use istio proxy because it does not run to completion

        spec:
          imagePullSecrets:
            - name: acrcred

          volumes:
            {{- range $root.Values.volumes }}
            - name: {{ .name }}

              {{- if .configMap }}
              configMap:
    {{ toYaml .configMap | indent 12 }}
              {{- end }}

              {{- if .emptyDir }}
              emptyDir:
    {{ toYaml .emptyDir | indent 12 }}
              {{- end }}

              {{- if .persistentVolumeClaim }}
              persistentVolumeClaim:
    {{ toYaml .persistentVolumeClaim | indent 12 }}
              {{- end }}

            {{- end }}
          containers:
            - name: {{ .name }}
              image: "{{ .repository }}:{{ .tag }}"
              command:
{{ toYaml .command | indent 16 }}
              volumeMounts:
                {{- range $root.Values.volumes }}
                - name: {{ .name }}
                  mountPath: {{ .mountPath }}
                  {{- if .readOnly }}
                  readOnly: {{ .readOnly }}
                  {{-  end }}
                  {{- if .subPath }}
                  subPath: {{ .subPath }}
                  {{-  end }}
                {{- end }}
              imagePullPolicy: {{ $root.Values.image.pullPolicy }}
              args:
{{ toYaml .args | indent 16 }}
              env:
                - name: WE_ENV
                  value: {{ $root.Values.geEnv }}
                - name: DEPLOY_SHA
                  value: {{ $root.Values.deploySHA }}
              {{- range $root.Values.envVars }}
                - name: "{{ .Name }}"
                  value: "{{ .Value }}"
              {{- end }}
          restartPolicy: {{ .restartPolicy }}
{{- end }}
