{{- if and .Values.hpa.enabled (or .Values.hpa.cpuUtilization .Values.hpa.memoryUtilization ) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-hpa
spec:
  minReplicas: {{ .Values.hpa.replicas.min }}
  maxReplicas: {{ .Values.hpa.replicas.max }}
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ .Values.appName }}
  metrics:
  {{- if and .Values.hpa.cpuUtilization .Values.resources.requests.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.cpuUtilization }}
  {{- end }}
  {{- if and .Values.hpa.memoryUtilization .Values.resources.requests.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.memoryUtilization }}
  {{- end }}
{{- end }}
