---
apiVersion: v1
data:
  robot_token: {{ printf "%s" .Values.robot_token | b64enc }}
kind: Secret
metadata:
  name: dingtalk-token.service-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
