---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-k8s-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # The ClusterRole “cluster-admin” resource allows access to all Kubernetes
  # resources in all API groups and is defined as part of the rbac-defaults
  # TODO: Permission maybe too open
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: vault-agent-k8s-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: vault-agent-k8s-role-binding
subjects:
  - kind: ServiceAccount
    name: vault-agent-k8s-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-agent-k8s-role
