---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-controller-manager
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
subsets:
- addresses:
  - ip: {{ .Values.masterIP }}
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: https-metrics
    port: 10257
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-scheduler
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
subsets:
- addresses:
  - ip: {{ .Values.masterIP }}
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kube-proxy
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
subsets:
- addresses:
  - ip: {{ .Values.masterIP }}
    targetRef:
      kind: Node
      name: norse
      uid: a466371b-4c17-4306-aa64-91d533b7b0a5
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP    
