apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "home-monitor-svc.fullname" . }}
  labels:
    k8s-monitoring: "true"
{{ include "home-monitor-svc.labels" . | indent 4 }}
spec:
  jobLabel: {{ .Values.appName }}
  endpoints:
  - honorLabels: true
    interval: 30s
    path: {{ .Values.service.path }}
    port: {{ .Values.service.port }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
