apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clash-client.fullname" . }}-secret
  labels:
    app: {{ template "clash-client.name" . }}
    chart: {{ template "clash-client.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: {{ .Values.clash_config_in_base64 }}
