{{- $root := . -}}
{{- if .Values.prometheus_cluster.enabled }}
{{- range $i, $e := until (.Values.prometheus_cluster.workers|int) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "k8s-prometheus-operator.name" $root }}
    chart: {{ template "k8s-prometheus-operator.chart" $root }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  name: cluster-scrape-config-{{ $i }}
type: Opaque
data:
  cluster-scrape-config.yaml: {{ include "cluster-scrape-config" (dict "workers" $root.Values.prometheus_cluster.workers "index" $i) | b64enc }}

---
{{- end }}
{{- end }}
