apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
subsets:
- addresses:
  - ip: {{ .Values.service.endpointIP }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    protocol: TCP
