{
 "title": "Grafana Internals",
 "tags": [ "k8s-addon" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Grafana Metrics Scarping Job Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=~\".*grafana.*\"}"
    }
   ]
  },
  {
   "title": "% Grafana Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\".*grafana.*\"} / kube_deployment_status_replicas{deployment=~\".*grafana.*\"} * 100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Grafana Dashboard Requests stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_api_dashboard_get_milliseconds_sum[1m]))",
     "legendFormat": "Dashboard GET"
    },
    {
     "expr": "sum(rate(grafana_api_dashboard_save_milliseconds_sum[1m]))",
     "legendFormat": "Dashboard Save"
    },
    {
     "expr": "sum(rate(grafana_api_dashboard_search_milliseconds_sum[1m]))",
     "legendFormat": "Dashboard Search"
    }
   ]
  },
  {
   "title": "Datasource Requests Time (Quantile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grafana_api_dataproxy_request_all_milliseconds[1m])) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(grafana_api_dataproxy_request_all_milliseconds_sum[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Grafana CPU Utilizaiton (Total / User / System)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{container_name=\"grafana\"}[5m]))\nby (container_name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(\n    rate(container_cpu_user_seconds_total{container_name=\"grafana\"}[5m]))\nby (container_name)",
     "legendFormat": "User"
    },
    {
     "expr": "sum(\n    rate(container_cpu_system_seconds_total{container_name=\"grafana\"}[5m]))\nby (container_name)",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Grafana Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"grafana\",name!~\"POD\"})\n  by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Grafana Network Utilization (Recevied / Transmitted)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*grafana.*\"}[5m])) by (name)\n",
     "legendFormat": "{{name}} (Received)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*grafana.*\"}[5m])) by (name)\n",
     "legendFormat": "{{name}} (Transmitted)"
    }
   ]
  }
 ]
}