{
 "title": "Kube Pods",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage By Pod",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage per Pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "{{ pod_name}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})\n",
       "legendFormat": "REQUEST"
      }
     ]
    },
    {
     "title": "CPU Usage per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "REQUEST"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
       "legendFormat": "LIMIT"
      }
     ]
    },
    {
     "title": "Network I/O per pod",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[1m])))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}