apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerreceivers.monitoring.alerts.com
  annotations:
    helm.sh/hook: crd-install
spec:
  group: monitoring.alerts.com
  names:
    kind: AlertManagerReceiver
    listKind: AlertManagerReceiverList
    plural: alertmanagerreceivers
    singular: alertmanagerreceiver
  scope: Namespaced
  version: v1alpha1
