apiVersion: v1
kind: Secret
metadata:
  name: grafana-sso-auth
  labels:
    app: {{ template "k8s-grafana.name" . }}
    chart: {{ template "k8s-grafana.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
data:
  GF_SERVER_ROOT_URL: {{ .Values.auth.root_url | b64enc | quote }}
  # Github SSO
  {{- if .Values.auth.github.enabled }}
  GF_AUTH_GITHUB_ENABLED:  {{ printf "TRUE" | b64enc | quote }}
  GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: {{ .Values.auth.github.organizations | b64enc | quote }}
  GF_AUTH_GITHUB_CLIENT_ID: {{ .Values.auth.github.client_id | b64enc | quote }}
  GF_AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth.github.client_secret | b64enc | quote }}
  {{- if (len .Values.auth.github.teamsID) gt 0 }}
  GF_AUTH_GITHUB_TEAM_IDS: {{ .Values.auth.github.teamsID | b64enc | quote }}
  {{- end }}
  {{- else }}
  GF_AUTH_GITHUB_ENABLED:  {{ printf "FALSE" | b64enc | quote }}
  {{- end }}

  # Okta SSO
  {{- if .Values.auth.okta.enabled }}
  GF_AUTH_GENERIC_OAUTH_ENABLED:  {{ printf "TRUE" | b64enc | quote }}
  {{- with .Values.auth.okta }}
  GF_AUTH_GENERIC_OAUTH_API_URL: {{ .api_url | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: {{ .auth_url | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .client_id | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .client_secret | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_NAME: {{ .name | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_SCOPES: {{ .scopes | b64enc | quote }}
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: {{ .token_url | b64enc | quote }}
  {{- end }}
  {{- else }}
  GF_AUTH_GENERIC_OAUTH_ENABLED:  {{ printf "FALSE" | b64enc | quote }}
  {{- end }}
