{{- if and .Values.hpa.enabled (or .Values.hpa.cpuUtilization .Values.hpa.memoryUtilization ) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: {{ include "k8s-grafana.name" . }}
    helm.sh/chart: {{ include "k8s-grafana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "k8s-grafana.fullname" . }}-hpa
spec:
  minReplicas: {{ .Values.hpa.replicas.min }}
  maxReplicas: {{ .Values.hpa.replicas.max }}
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ .Values.grafana.nameOverride }}
  metrics:
  {{- if and .Values.hpa.cpuUtilization .Values.grafana.resources.requests.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.cpuUtilization }}
  {{- end }}
  {{- if and .Values.hpa.memoryUtilization .Values.grafana.resources.requests.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.memoryUtilization }}
  {{- end }}
{{- end }}
