apiVersion: v1
appVersion: "1.0"
description: A Helm chart for alert-operator
name: alert-operator
version: 0.1.4
sources:
  - https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources
  - https://github.com/operator-framework/operator-sdk
