apiVersion: monitoring.alerts.com/v1alpha1
kind: AlertManagerRoute
metadata:
  name: {{ template "k8s-alert-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-alert-router.name" . }}
    helm.sh/chart: {{ include "k8s-alert-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  target_configuration:
    secret_name: {{ required "Please specify the alertmanager secret name for selectors" .Values.alerts.selectors.secretName }}
    # target the namespace of where the alert manager is running
    namespace: {{ required "Please specify the alertmanager namespace for selectors" .Values.alerts.selectors.alertManagerNamespace }}
  routes:
      # receiver name
    - receiver: {{ required "Please specify the receiver name for warning alerts" .Values.alerts.receivers.warningReceiverName }}
      # Match labels & value
      match:
        namespace: {{ .Release.Namespace }}
        alert_source: {{ .Release.Name }}
      match_re:
        severity: .*
    {{- if .Values.alerts.receivers.criticalReceiverName }}
      continue: true
      routes:
        # db_multi_alert sends alert to pagerduty and slack
        - receiver: {{ .Values.alerts.receivers.criticalReceiverName }}
          # Match labels & value
          match:
            severity: critical
            namespace: {{ .Release.Namespace }}
            alert_source: {{ .Release.Name }}
    {{- end }}
