{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "k8s-nginx-ingress.name" . }}
    chart: {{ template "k8s-nginx-ingress.chart" . }}
    release: {{ .Release.name }}
    heritage: {{ .Release.Service }}
    k8s-monitoring: "true"
  name: {{ template "k8s-nginx-ingress.fullname" . }}
spec:
  jobLabel: nginx-ingress
  selector:
    matchLabels:
      app: nginx-ingress
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace}}
  endpoints:
    - port: metrics
      interval: 30s
{{ end }}
