{{- if .Values.crd.install }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerroutes.monitoring.alerts.com
  labels:
    app.kubernetes.io/name: {{ include "alert-operator.name" . }}
    helm.sh/chart: {{ include "alert-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: monitoring.alerts.com
  names:
    kind: AlertManagerRoute
    listKind: AlertManagerRouteList
    plural: alertmanagerroutes
    singular: alertmanagerroute
  scope: Namespaced
  version: v1alpha1
{{- end }}
