apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alert-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alert-operator.name" . }}
    helm.sh/chart: {{ include "alert-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alert-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alert-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "alert-operator.fullname" . }}
          # Replace this with the built image name
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: {{ .Values.service.port }}
            name: metrics
          command:
          - alert-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "alert-operator"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      serviceAccountName: {{ include "alert-operator.fullname" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range $secret := .Values.imagePullSecrets }}
{{ list $secret | toYaml | indent 9 -}}
{{- end -}}
{{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
