kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "alert-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alert-operator.name" . }}
    helm.sh/chart: {{ include "alert-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "alert-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "alert-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
